/* Technet Space: front-end prototype. No AI requests are executed without a configured backend. */
const rooms=[
  {id:'controle',name:'Central de controle',icon:'▦',description:'Onde suas ideias se tornam trabalho em andamento.',color:'#8e76e2'},
  {id:'comercial',name:'Comercial',icon:'◈',description:'Um espaço para acompanhar propostas e vendas.',color:'#d69876'},
  {id:'operacoes',name:'Operações',icon:'⌁',description:'Planejamento, equipes e rotas em um só lugar.',color:'#78b8ab'},
  {id:'convivencia',name:'Convivência',icon:'☕',description:'Uma pausa para encontrar a equipe.',color:'#d0ad72'}
];
const agents=[
  {id:'operacoes',name:'Lia',role:'Operações',symbol:'◈',color:'#856bd7',description:'Organiza demandas, equipes, rotas e prioridades.',words:['equipe','rota','tarefa','operação','tecnico','técnico','escala','mdu','obra','endereço','prazo']},
  {id:'dados',name:'Noah',role:'Dados e indicadores',symbol:'▥',color:'#568fbd',description:'Analisa planilhas, metas, relatórios e indicadores.',words:['dados','planilha','relatório','meta','grafico','gráfico','indicador','análise','comparar','resultado']},
  {id:'comercial',name:'Maya',role:'Comercial',symbol:'✦',color:'#c47c7e',description:'Ajuda a estruturar propostas e organizar vendas.',words:['venda','cliente','proposta','comercial','contrato','negociação','lead','orçamento']},
  {id:'criacao',name:'Theo',role:'Criação',symbol:'◆',color:'#ba985e',description:'Prepara textos, comunicados e ideias de apresentação.',words:['texto','mensagem','comunicado','imagem','design','apresentação','criar','escrever','post']}
];
const $=s=>document.querySelector(s);
const safeRead=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let tasks=safeRead('technet-space-tasks',[]),chats=safeRead('technet-space-chats',{});
let room=rooms[0],view='space',zoom=1,lastFrame=0;
const player={x:576,y:430,targetX:576,targetY:430,dir:1};
const canvas=$('#world'),ctx=canvas.getContext('2d');
const decor={controle:['PAINEL CENTRAL','PROJETOS','REUNIÕES'],comercial:['VENDAS','PROPOSTAS','CLIENTES'],operacoes:['EQUIPES','ROTAS','PLANEJAMENTO'],convivencia:['CAFÉ','DESCANSO','ENCONTROS']};

function save(){localStorage.setItem('technet-space-tasks',JSON.stringify(tasks));localStorage.setItem('technet-space-chats',JSON.stringify(chats))}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3200)}
function roomNav(){const nav=$('#roomList');nav.replaceChildren();rooms.forEach(r=>{const b=document.createElement('button');b.className='room-button'+(r.id===room.id?' active':'');b.innerHTML=`<span class="room-icon">${r.icon}</span><span>${r.name}</span><small>›</small>`;b.onclick=()=>chooseRoom(r);nav.append(b)});$('#roomCount').textContent=String(rooms.length).padStart(2,'0')}
function agentNav(){const list=$('#agentsList');list.replaceChildren();agents.forEach(a=>{const b=document.createElement('button');b.className='agent-row';b.innerHTML=`<span class="agent-face" style="--agent:${a.color}">${a.symbol}</span><span class="agent-copy"><strong>${a.name}</strong><small>${a.role}</small></span>`;b.onclick=()=>{showView('people');$('#peopleGrid').querySelector(`[data-agent="${a.id}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})};list.append(b)});const grid=$('#peopleGrid');grid.replaceChildren();agents.forEach(a=>{const card=document.createElement('article');card.className='person-card';card.dataset.agent=a.id;card.innerHTML=`<span class="agent-face" style="--agent:${a.color}">${a.symbol}</span><h3>${a.name}</h3><small>● Disponível · ${a.role}</small><p>${a.description}</p><button class="outline-button">Pedir ajuda ↗</button>`;card.querySelector('button').onclick=()=>{openModal();$('#taskText').focus()};grid.append(card)})}
function chooseRoom(next){room=next;player.x=576;player.y=430;player.targetX=576;player.targetY=430;$('#roomTitle').textContent=next.name;$('#roomDescription').textContent=next.description;$('#topRoom').textContent=next.name;$('#mapRoom').textContent=next.name;$('#chatRoom').textContent=next.name;roomNav();renderChat();showView('space')}
function showView(next){view=next;$('#spaceView').classList.toggle('hidden',next!=='space');$('#tasksView').classList.toggle('hidden',next!=='tasks');$('#peopleView').classList.toggle('hidden',next!=='people');document.querySelectorAll('.rail-item').forEach(b=>b.classList.toggle('active',b.dataset.view===next));if(next==='tasks')renderTasks()}
function route(text){const normalized=text.toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');let best=agents[0],score=0;for(const a of agents){const matches=a.words.filter(w=>normalized.includes(w.normalize('NFD').replace(/[\u0300-\u036f]/g,''))).length;if(matches>score){score=matches;best=a}}return {agent:best,reason:score?'Sugestão baseada nos termos do seu pedido.':'Sugestão padrão para organizar e encaminhar o pedido.'}}
function updateSuggestion(){const match=route($('#taskText').value);$('#suggestedAgent').textContent=`${match.agent.name} · ${match.agent.role}`;$('#suggestedReason').textContent=match.reason}
function openModal(){$('#taskModal').classList.remove('hidden');updateSuggestion();$('#taskText').focus()}
function closeModal(){$('#taskModal').classList.add('hidden');$('#taskForm').reset();updateSuggestion()}
function renderTasks(){const list=$('#taskList');list.replaceChildren();$('#statWorking').textContent=tasks.filter(t=>t.status==='pendente').length;$('#statDone').textContent=tasks.filter(t=>t.status==='concluido').length;if(!tasks.length){const empty=document.createElement('div');empty.className='empty-state';empty.innerHTML='<span>✦</span><h3>Seu próximo pedido começa aqui</h3><p>Descreva uma tarefa e acompanhe a sugestão de encaminhamento.</p>';list.append(empty);return}tasks.slice().reverse().forEach(t=>{const a=agents.find(x=>x.id===t.agent)||agents[0];const card=document.createElement('article');card.className='task-card';const face=document.createElement('span');face.className='agent-face';face.style.setProperty('--agent',a.color);face.textContent=a.symbol;const copy=document.createElement('div');copy.className='task-copy';const title=document.createElement('strong');title.textContent=t.text;const meta=document.createElement('p');meta.textContent=`Sugerido para ${a.name} · ${new Date(t.created).toLocaleString('pt-BR')} · Sem execução de IA conectada`;copy.append(title,meta);const status=document.createElement('span');status.className='status';status.textContent='Aguardando integração';card.append(face,copy,status);list.append(card)})}
function renderActivity(){const list=$('#activityList');list.replaceChildren();const entries=tasks.slice(-4).reverse();$('#activityCount').textContent=String(entries.length);if(!entries.length){const el=document.createElement('div');el.className='activity-item';el.innerHTML='<div class="activity-symbol">✦</div><div><strong>Espaço pronto para começar</strong><p>Envie o primeiro pedido e veja seu encaminhamento aparecer aqui.</p><time>Agora</time></div>';list.append(el);return}entries.forEach(t=>{const item=document.createElement('div');item.className='activity-item';item.innerHTML='<div class="activity-symbol">✦</div><div><strong>Novo pedido registrado</strong><p></p><time></time></div>';item.querySelector('p').textContent=`Sugestão: ${agents.find(a=>a.id===t.agent)?.name||'Lia'} · aguardando integração`;item.querySelector('time').textContent=new Date(t.created).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});list.append(item)})}
function renderChat(){const list=$('#chatMessages');list.replaceChildren();const messages=chats[room.id]||[];if(!messages.length){const m=document.createElement('div');m.className='chat-message';m.innerHTML='<span class="mini-avatar" style="background:#6d5ba9;color:white">✦</span><div><strong>Technet Space</strong><p>Bem-vindo à sala. As mensagens ficam salvas neste navegador.</p></div>';list.append(m)}messages.forEach(m=>{const el=document.createElement('div');el.className='chat-message';const avatar=document.createElement('span');avatar.className='mini-avatar';avatar.textContent=m.name.slice(0,1).toUpperCase();const body=document.createElement('div');const name=document.createElement('strong');name.textContent=m.name;const p=document.createElement('p');p.textContent=m.text;body.append(name,p);el.append(avatar,body);list.append(el)});list.scrollTop=list.scrollHeight}

function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function label(text,x,y,size=12,color='#cbd0e4'){ctx.fillStyle=color;ctx.font=`700 ${size}px Outfit, sans-serif`;ctx.textAlign='center';ctx.fillText(text,x,y)}
function drawAvatar(x,y,color,initial,name,walking=false){ctx.fillStyle='#171b2b66';ctx.beginPath();ctx.ellipse(x,y+19,22,9,0,0,Math.PI*2);ctx.fill();rounded(x-16,y-20,32,37,10,color,'#ffffff88');ctx.fillStyle='#f4c8a5';ctx.beginPath();ctx.arc(x,y-23,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#413044';ctx.beginPath();ctx.arc(x,y-28,11,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='800 13px Outfit';ctx.textAlign='center';ctx.fillText(initial,x,y+5);rounded(x-name.length*4-8,y-55,name.length*8+16,21,7,'#1c2035e8');label(name,x,y-40,11,'#fff');if(walking){ctx.strokeStyle='#ffdaa8';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-6,y+17);ctx.lineTo(x-8,y+22);ctx.moveTo(x+6,y+17);ctx.lineTo(x+8,y+22);ctx.stroke()}}
function plant(x,y){ctx.fillStyle='#282c43';ctx.beginPath();ctx.ellipse(x,y+9,18,8,0,0,Math.PI*2);ctx.fill();rounded(x-10,y-5,20,17,3,'#a86f65');for(let k=-1;k<=1;k++){ctx.fillStyle=k?'#4c9a78':'#67b786';ctx.beginPath();ctx.ellipse(x+k*9,y-17-Math.abs(k)*4,7,15,k*.45,0,Math.PI*2);ctx.fill()}}
function desk(x,y,color='#aa856f'){rounded(x-42,y-21,84,48,5,'#222944');rounded(x-46,y-26,92,41,7,color,'#ddbaa2');rounded(x-24,y-37,48,27,4,'#313752','#8a95b0');rounded(x-20,y-34,40,20,2,'#53617f');rounded(x-9,y+20,18,23,4,'#414d65')}
function sofa(x,y,color='#9172ad'){rounded(x-50,y-19,100,49,12,color,'#c9a9d1');rounded(x-43,y-32,86,20,7,color);ctx.strokeStyle='#cdb4dd';ctx.beginPath();ctx.moveTo(x,y-24);ctx.lineTo(x,y+22);ctx.stroke()}
function drawWorld(now){const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const theme=room.color;ctx.fillStyle='#30344b';ctx.fillRect(0,0,w,h);rounded(60,46,w-120,h-91,17,'#383d58','#77728f');ctx.save();ctx.beginPath();ctx.roundRect(66,52,w-132,h-103,13);ctx.clip();ctx.fillStyle='#4a5068';ctx.fillRect(66,52,w-132,h-103);for(let y=58;y<h-46;y+=32){for(let x=70;x<w-60;x+=32){ctx.strokeStyle='#70738b22';ctx.strokeRect(x,y,32,32)}}rounded(88,74,303,184,10,'#414861','#7d8199');rounded(412,74,329,184,10,'#434b65','#82859d');rounded(762,74,300,184,10,'#414861','#7d8199');rounded(88,283,303,261,10,'#454c64','#7d8199');rounded(412,283,329,261,10,'#41485f','#7d8199');rounded(762,283,300,261,10,'#464e65','#7d8199');rounded(432,283,284,26,4,theme);label(decor[room.id][0],576,113,15,'#e9e9f2');label(decor[room.id][1],242,113,15,'#e9e9f2');label(decor[room.id][2],912,113,15,'#e9e9f2');
  // Room furniture remains navigational decoration; avatar movement stays in the common open floor.
  desk(169,178);desk(298,178);desk(495,183);desk(656,183);desk(836,178);desk(979,178);sofa(236,386,'#886ba4');sofa(577,386,'#6e91ac');sofa(913,386,'#a97983');rounded(178,459,120,22,9,'#92735c');rounded(518,463,116,24,9,'#9f816a');rounded(851,463,125,24,9,'#a08066');plant(105,293);plant(384,296);plant(756,291);plant(1036,294);plant(105,509);plant(1038,511);
  rounded(364,554,424,22,8,'#303549');label('TECHNET  ✦  SUA EQUIPE, EM UM SÓ LUGAR',576,570,12,'#adb3cb');
  agents.forEach((a,i)=>{const x=[175,500,842,960][i]+Math.sin(now/1300+i*2)*13,y=[218,225,221,439][i]+Math.cos(now/1700+i)*6;drawAvatar(x,y,a.color,a.symbol,a.name)});drawAvatar(player.x,player.y,'#8166c2','C','Você',Math.abs(player.targetX-player.x)+Math.abs(player.targetY-player.y)>4);ctx.restore();if(zoom!==1){/* zoom is applied to the DOM canvas to preserve crisp hit testing */}requestAnimationFrame(drawWorld)}
function move(){const dx=player.targetX-player.x,dy=player.targetY-player.y,dist=Math.hypot(dx,dy);if(dist>2){const step=Math.min(dist,3.5);player.x+=dx/dist*step;player.y+=dy/dist*step}requestAnimationFrame(move)}
canvas.addEventListener('click',e=>{const rect=canvas.getBoundingClientRect();player.targetX=Math.max(106,Math.min(1045,(e.clientX-rect.left)/rect.width*canvas.width));player.targetY=Math.max(300,Math.min(525,(e.clientY-rect.top)/rect.height*canvas.height))});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(view!=='space'||!$('#taskModal').classList.contains('hidden')||['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;const moves={ArrowUp:[0,-38],w:[0,-38],ArrowDown:[0,38],s:[0,38],ArrowLeft:[-38,0],a:[-38,0],ArrowRight:[38,0],d:[38,0]};const delta=moves[e.key];if(delta){e.preventDefault();player.targetX=Math.max(106,Math.min(1045,player.targetX+delta[0]));player.targetY=Math.max(300,Math.min(525,player.targetY+delta[1]))}});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));['#sideNewTask','#topNewTask','#bottomNewTask','#tasksNewTask'].forEach(s=>$(s).onclick=openModal);$('#closeModal').onclick=closeModal;$('#taskModal').onclick=e=>{if(e.target===$('#taskModal'))closeModal()};$('#taskText').addEventListener('input',updateSuggestion);
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const content=$('#taskText').value.trim();if(content.length<8)return;const choice=route(content);tasks.push({id:crypto.randomUUID(),text:content,agent:choice.agent.id,status:'pendente',created:new Date().toISOString()});save();renderTasks();renderActivity();closeModal();showView('tasks');toast(`Pedido registrado. Agente sugerido: ${choice.agent.name}.`)});
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;(chats[room.id]??=[]).push({name:'Você',text});save();input.value='';renderChat()});
$('#helpButton').onclick=()=>toast('Use WASD, as setas ou clique no mapa para caminhar.');
function setZoom(n){zoom=Math.max(.8,Math.min(1.3,n));canvas.style.width=`${Math.round(zoom*100)}%`;$('#zoomLabel').textContent=`${Math.round(zoom*100)}%`}
$('#zoomIn').onclick=()=>setZoom(zoom+.1);$('#zoomOut').onclick=()=>setZoom(zoom-.1);
roomNav();agentNav();renderTasks();renderActivity();renderChat();updateSuggestion();requestAnimationFrame(drawWorld);requestAnimationFrame(move);
