import test from 'node:test';
import assert from 'node:assert/strict';
import {createHandler} from '../worker/index.js';
import {routeOrder} from '../public/agents.js';
const request=(body,headers={})=>new Request('https://office.example/api/execute',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
const env={GROQ_API_KEY:'test-secret-not-real',AI_PROVIDER:'groq',AI_MODEL:'test-model'};

test('unconfigured API retains honest unavailable status and never calls a provider',async()=>{const app=createHandler({},()=>{throw new Error('should not fetch')});const status=await app.fetch(new Request('https://office.example/api/status'));assert.deepEqual(await status.json(),{configured:false,provider:'OpenAI',model:null});const run=await app.fetch(request({prompt:'Organize as tarefas da equipe'}));assert.equal(run.status,503)});
test('a routed order uses the agent context and returns the real provider output',async()=>{let body;let key;const app=createHandler({},async(url,init)=>{assert.equal(url,'https://api.groq.com/openai/v1/chat/completions');key=init.headers.Authorization;body=JSON.parse(init.body);return Response.json({choices:[{message:{content:'Plano de ação produzido pelo provedor.'},finish_reason:'stop'}]})});const reply=await app.fetch(request({prompt:'Monte uma proposta de vendas',agentId:'maya'}),env);const data=await reply.json();assert.equal(key,'Bearer test-secret-not-real');assert.match(body.messages[0].content,/Maya/);assert.equal(data.output,'Plano de ação produzido pelo provedor.');assert.equal(data.agentId,'maya');assert.ok(!JSON.stringify(data).includes(env.GROQ_API_KEY))});
test('reject cross-origin execution, invalid agent and oversized payload before a provider call',async()=>{const app=createHandler({},()=>{throw new Error('should not fetch')});assert.equal((await app.fetch(request({prompt:'Crie um comunicado válido'},{Origin:'https://other.example'}),env)).status,403);assert.equal((await app.fetch(request({prompt:'Crie um comunicado válido',agentId:'inventado'}),env)).status,400);assert.equal((await app.fetch(request({prompt:'x'.repeat(33000)}),env)).status,413)});
test('provider rejection cannot leak provider error details or secrets',async()=>{const app=createHandler({},async()=>new Response(JSON.stringify({error:{message:'secret diagnostic'}}),{status:401}));const reply=await app.fetch(request({prompt:'Organize uma tarefa de teste'}),env);assert.equal(reply.status,502);assert.ok(!(await reply.text()).includes('secret diagnostic'))});
test('empty provider results are errors, not completed deliveries',async()=>{const app=createHandler({},async()=>Response.json({choices:[{message:{content:''}}]}));const reply=await app.fetch(request({prompt:'Organize uma tarefa de teste'}),env);assert.equal(reply.status,502)});
test('serves known assets only and supports HEAD',async()=>{const app=createHandler({'/index.html':{content:'<h1>Central</h1>',type:'text/html'}});assert.equal((await app.fetch(new Request('https://office.example/'))).status,200);const head=await app.fetch(new Request('https://office.example/',{method:'HEAD'}));assert.equal(await head.text(),'');assert.equal((await app.fetch(new Request('https://office.example/.env'))).status,404)});
test('agent routing covers commercial, development and data requests',()=>{assert.equal(routeOrder('Corrija o bug no código JavaScript').id,'ada');assert.equal(routeOrder('Crie proposta comercial para cliente').id,'maya');assert.equal(routeOrder('Analise os dados da planilha de indicadores').id,'davi')});
