import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from './supabase';

const CIDADES = [
  ['NATAL', 'Natal - RN'], ['MOSSORO', 'Mossoró - RN'],
  ['FORTALEZA', 'Fortaleza - CE'], ['RECIFE', 'Recife - PE'],
];
const STATUS = ['EM CONSTRUÇÃO','TENTANDO ACESSO','CONSTRUÍDO','ACESSO NEGADO','OBSTRUÇÃO','FOLGA','FERIAS'];
const MENU = [['dashboard','⌂','Início'],['rota','☷','Rotas'],['base','▤','Base geral'],['historico','◴','Histórico'],['proximas','▦','Planejamento'],['metas','◎','Metas'],['config','⚙','Configurações']];
const n = (v='') => String(v).trim().toUpperCase();
const hoje = () => new Date().toISOString().slice(0,10);
const construida = (v) => { const s=n(v); return !s.startsWith('EM CONSTRU') && (s.includes('CONSTRUÍDO') || s.includes('CONSTRUIDO') || s.includes('LIBERADO')); };
const bloqueio = (v) => ['ACESSO NEGADO','OBSTRUÇÃO'].includes(n(v));
const fmt = (v) => !v ? '—' : new Date(v).toLocaleDateString('pt-BR');
const codigoEndereco = (v='') => String(v).trim().match(/^(\d{6,12})/)?.[1] || null;
const podeEditar = (role) => ['ADMIN','GERENTE','CONTROLADOR'].includes(role);
const nomeCidade = (id) => CIDADES.find(([x]) => x===id)?.[1] || id || '—';

async function listarTudo(tabela, ordem='created_at', asc=false) {
  let de=0, todos=[];
  while (true) {
    const { data, error } = await supabase.from(tabela).select('*').order(ordem,{ascending:asc}).range(de,de+999);
    if (error) throw error;
    todos.push(...(data||[]));
    if (!data || data.length < 1000) break;
    de += 1000;
  }
  return todos;
}

function Login() {
  const [email,setEmail]=useState(''); const [senha,setSenha]=useState(''); const [erro,setErro]=useState(''); const [loading,setLoading]=useState(false);
  async function entrar(e){e.preventDefault();setLoading(true);setErro('');const {error}=await supabase.auth.signInWithPassword({email,password:senha});if(error)setErro('Não foi possível entrar. Confira e-mail e senha.');setLoading(false)}
  return <div className="login-page"><div className="login-shell"><section className="login-visual"><div className="brand login-brand"><span className="brand-mark">T</span><div><strong>TechNET</strong><small>Rotas MDU</small></div></div><h2>Organize a operação.<br/>Acompanhe cada rota.</h2><p>Rotas, equipes, impedimentos e produção em um único espaço de trabalho.</p><div className="login-preview"><span/><span/><span/></div></section><form className="login-card" onSubmit={entrar}><small className="eyebrow">BEM-VINDO</small><h1>Entrar no TechNET</h1><p>Use a mesma conta MDU cadastrada no sistema.</p><label>E-mail</label><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="nome@empresa.com"/><label>Senha</label><input type="password" required value={senha} onChange={e=>setSenha(e.target.value)} placeholder="Sua senha"/>{erro&&<div className="error-box">{erro}</div>}<button className="primary login-button" disabled={loading}>{loading?'Entrando...':'Entrar'}</button></form></div></div>;
}

export default function App(){
  const [sessao,setSessao]=useState(null),[perfil,setPerfil]=useState(null),[pagina,setPagina]=useState('dashboard');
  const [rota,setRota]=useState([]),[base,setBase]=useState([]),[historico,setHistorico]=useState([]),[proximas,setProximas]=useState([]),[carregando,setCarregando]=useState(true),[aviso,setAviso]=useState('');
  useEffect(()=>{supabase.auth.getSession().then(({data})=>setSessao(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSessao(s));return()=>subscription.unsubscribe()},[]);
  useEffect(()=>{if(!sessao){setPerfil(null);return}supabase.from('profiles').select('id,name,email,role,city_id').eq('auth_user_id',sessao.user.id).maybeSingle().then(({data})=>setPerfil(data))},[sessao]);
  const carregar=useCallback(async()=>{if(!sessao)return;setCarregando(true);try{const [r,b,h,q]=await Promise.all([listarTudo('route_daily','route_date',false),listarTudo('route_general','construction_date',false),listarTudo('route_history','occurred_at',false),listarTudo('route_queue','priority',true)]);setRota(r);setBase(b);setHistorico(h);setProximas(q)}catch(e){setAviso(e.message)}finally{setCarregando(false)}},[sessao]);
  useEffect(()=>{carregar()},[carregar]);
  useEffect(()=>{if(!sessao)return;const canal=supabase.channel('rotas-live').on('postgres_changes',{event:'*',schema:'public',table:'route_daily'},carregar).on('postgres_changes',{event:'*',schema:'public',table:'route_queue'},carregar).subscribe();return()=>supabase.removeChannel(canal)},[sessao,carregar]);
  if(!sessao)return <Login/>;
  if(carregando&&!rota.length)return <div className="loading"><div className="loader"/><b>Carregando rotas...</b></div>;
  const editavel=podeEditar(perfil?.role);
  async function auditar(acao,entidade,id,detalhes={}){await supabase.from('route_audit').insert({actor_id:sessao.user.id,action:acao,entity:entidade,entity_id:id,details:detalhes})}
  async function automatizar(item,novoStatus){
    if(construida(novoStatus)){
      const codigo=item.property_code||codigoEndereco(item.address);let existente=null;
      if(codigo){const {data}=await supabase.from('route_general').select('id').eq('property_code',codigo).limit(1).maybeSingle();existente=data}
      if(!existente&&item.address){const {data}=await supabase.from('route_general').select('id').eq('city_id',item.city_id).ilike('address',item.address.trim()).limit(1).maybeSingle();existente=data}
      const registro={city_id:item.city_id,team:[item.technician,item.assistant].filter(Boolean).join(' E '),project_type:item.project_type,synergy:item.synergy,property_code:codigo,address:item.address||'',hps:Number(item.hps||0),construction_date:item.route_date||hoje(),month_label:new Date().toLocaleDateString('pt-BR',{month:'long',year:'2-digit'}),status:'Construído/Liberado',notes:item.notes,source:'ROTA'};
      if(existente)await supabase.from('route_general').update({...registro,updated_at:new Date().toISOString()}).eq('id',existente.id);else await supabase.from('route_general').insert(registro);
    }
    if(bloqueio(novoStatus))await supabase.from('route_history').insert({city_id:item.city_id,route_date:item.route_date||hoje(),team:[item.technician,item.assistant].filter(Boolean).join(' E '),address:item.address,hps:Number(item.hps||0),blocks:Number(item.blocks||0),status:novoStatus,start_date:item.start_date,synergy:item.synergy,notes:'Registrado automaticamente pelo sistema'});
  }
  async function alterarRota(id,campo,valor){const item=rota.find(x=>x.id===id);if(!item||!editavel)return;const patch={[campo]:valor,updated_at:new Date().toISOString()};if(campo==='address')patch.property_code=codigoEndereco(valor);const {error}=await supabase.from('route_daily').update(patch).eq('id',id);if(error)return setAviso(error.message);if(campo==='status')await automatizar(item,valor);await auditar('ALTERAR_ROTA','route_daily',id,{campo,valor});await carregar()}
  const props={rota,base,historico,proximas,alterarRota,carregar,editavel,sessao,perfil,auditar,setAviso};
  return <div className="app-shell"><aside className="sidebar"><div className="workspace-head"><span className="brand-mark">T</span><div><strong>TechNET</strong><small>Operação MDU</small></div><button className="workspace-switch">⌄</button></div><button className="create-button" onClick={()=>setPagina('rota')}><span>＋</span>Criar</button><div className="nav-group"><small>TRABALHO</small><nav>{MENU.slice(0,5).map(([id,ico,label])=><button key={id} className={pagina===id?'active':''} onClick={()=>setPagina(id)}><span>{ico}</span>{label}</button>)}</nav></div><div className="nav-group"><small>GESTÃO</small><nav>{MENU.slice(5).map(([id,ico,label])=><button key={id} className={pagina===id?'active':''} onClick={()=>setPagina(id)}><span>{ico}</span>{label}</button>)}</nav></div><div className="sidebar-project"><span className="project-dot">R</span><div><b>Rotas MDU 2026</b><small>{perfil?.city_id||'Todas as cidades'}</small></div></div><div className="sidebar-foot"><div className="avatar">{(perfil?.name||'AD').slice(0,2).toUpperCase()}</div><div><b>{perfil?.name||sessao.user.email}</b><small>{perfil?.role||'USUÁRIO'}</small></div><button onClick={()=>supabase.auth.signOut()} title="Sair">↗</button></div></aside><main className="main"><header className="globalbar"><div className="global-search"><span>⌕</span><input placeholder="Pesquisar no TechNET"/></div><div className="global-actions"><span className="live-pill"><i/>Tempo real</span><button className="round-button">?</button><div className="avatar">{(perfil?.name||'AD').slice(0,2).toUpperCase()}</div></div></header><section className="project-header"><div className="project-heading"><span className="project-icon">R</span><div><small>OPERAÇÃO MDU</small><h1>{MENU.find(x=>x[0]===pagina)?.[2]}</h1></div><button className="star-button">☆</button></div><div className="project-actions"><div className="member-stack"><span>NT</span><span>FT</span><span>RC</span></div><button className="share-button">Compartilhar</button><button className="more-button">•••</button></div></section>{aviso&&<div className="notice" onClick={()=>setAviso('')}>{aviso}</div>}<section className="content">{pagina==='dashboard'&&<Dashboard {...props}/>} {pagina==='rota'&&<Rota {...props}/>} {pagina==='base'&&<Base {...props}/>} {pagina==='historico'&&<Historico {...props}/>} {pagina==='proximas'&&<Fila {...props}/>} {pagina==='metas'&&<Metas {...props}/>} {pagina==='config'&&<Configuracoes perfil={perfil}/>}</section></main></div>;
}

function Dashboard({rota,base}){const ativos=rota.filter(x=>!['FOLGA','FERIAS'].includes(n(x.status))),hps=ativos.reduce((s,x)=>s+Number(x.hps||0),0),blocos=ativos.reduce((s,x)=>s+Number(x.blocks||0),0),constr=ativos.filter(x=>construida(x.status)).length,alertas=ativos.filter(x=>n(x.status)==='TENTANDO ACESSO'&&x.start_date&&(Date.now()-new Date(x.start_date).getTime())/86400000>=2);return <><div className="kpi-grid">{[['HPs em rota',hps,'∑'],['Blocos em rota',blocos,'▦'],['Construídos',constr,'✓'],['Alertas de acesso',alertas.length,'!']].map(([t,v,i])=><div className="kpi" key={t}><div><small>{t}</small><strong>{v}</strong></div><span>{i}</span></div>)}</div><div className="grid-2"><Panel titulo="Situação por cidade" subtitulo="Rota operacional atual"><div className="city-list">{CIDADES.map(([id,nome])=>{const a=ativos.filter(x=>x.city_id===id),total=a.reduce((s,x)=>s+Number(x.hps||0),0);return <div className="city-row" key={id}><div><b>{nome.split(' - ')[0]}</b><small>{a.length} equipes</small></div><div className="bar"><i style={{width:`${Math.min(100,total/4)}%`}}/></div><strong>{total} HPs</strong></div>})}</div></Panel><Panel titulo="Alertas operacionais" subtitulo="Tentando acesso há 2 dias ou mais">{alertas.length?alertas.map(x=><div className="alert" key={x.id}><span>!</span><div><b>{x.technician} / {x.assistant}</b><small>{x.address} · desde {fmt(x.start_date)}</small></div></div>):<Empty texto="Nenhum alerta crítico."/>}</Panel></div><Panel titulo="Base histórica" subtitulo="Dados consolidados da aba Geral"><div className="history-summary"><K t="Registros" v={base.length}/><K t="Liberados" v={base.filter(x=>n(x.status).includes('LIBER')).length}/><K t="HPs históricos" v={base.reduce((s,x)=>s+Number(x.hps||0),0).toLocaleString('pt-BR')}/><K t="Cidades" v={new Set(base.map(x=>x.city_id)).size}/></div></Panel></>}

function Rota({rota,alterarRota,carregar,editavel,auditar,sessao}){
  const [cidade,setCidade]=useState('TODAS'),[novo,setNovo]=useState(false),[visao,setVisao]=useState('lista');
  const lista=cidade==='TODAS'?rota:rota.filter(x=>x.city_id===cidade);
  return <><div className="viewbar"><div className="view-tabs"><button className={visao==='lista'?'active':''} onClick={()=>setVisao('lista')}><span>☷</span>Lista</button><button className={visao==='quadro'?'active':''} onClick={()=>setVisao('quadro')}><span>▦</span>Quadro</button></div><div className="view-actions"><select className="city-filter" value={cidade} onChange={e=>setCidade(e.target.value)}><option value="TODAS">Todas as cidades</option>{CIDADES.map(([id,nome])=><option value={id} key={id}>{nome}</option>)}</select><button className="filter-button">☷ Filtrar</button>{editavel&&<button className="primary" onClick={()=>setNovo(!novo)}>＋ Adicionar rota</button>}</div></div>{novo&&<NovaRota onClose={()=>setNovo(false)} carregar={carregar} auditar={auditar} sessao={sessao}/>} {visao==='lista'?<RotaLista lista={lista} alterarRota={alterarRota} editavel={editavel}/>:<RotaQuadro lista={lista} alterarRota={alterarRota} editavel={editavel}/>}</>;
}

function CelulaEditavel({valor='',tipo='text',editavel=true,onSalvar,classe=''}){
  const [local,setLocal]=useState(valor??'');
  useEffect(()=>setLocal(valor??''),[valor]);
  function salvar(){const v=tipo==='number'?Number(local||0):local;if(String(v)!==String(valor??''))onSalvar(v)}
  return <input className={`sheet-input ${classe}`} disabled={!editavel} type={tipo} value={local} onChange={e=>setLocal(e.target.value)} onBlur={salvar} onKeyDown={e=>{if(e.key==='Enter'){e.currentTarget.blur()}}}/>;
}

function RotaLista({lista,alterarRota,editavel}){
  const grupos=CIDADES.map(([id,nome])=>({id,nome,itens:lista.filter(x=>x.city_id===id)})).filter(g=>g.itens.length);
  const conhecidos=new Set(CIDADES.map(([id])=>id));
  const outros=lista.filter(x=>!conhecidos.has(x.city_id));
  if(outros.length)grupos.push({id:'OUTROS',nome:'Outras cidades',itens:outros});
  return <div className="panel table-panel sheet-route"><div className="sheet-help"><div><b>Rota diária</b><small>Edite direto nas células. Texto salva ao pressionar Enter ou sair da célula.</small></div><span>{lista.length} equipes · {lista.reduce((s,x)=>s+Number(x.hps||0),0)} HPs</span></div><div className="table-wrap"><table><thead><tr><th>Fusão</th><th>Técnico</th><th>Auxiliar</th><th>Endereço</th><th>HP</th><th>Blocos</th><th>Status</th><th>Data de início</th><th>Sinergia</th><th>Tipo de projeto</th></tr></thead><tbody>{grupos.map(g=><React.Fragment key={g.id}><tr className="city-group-row"><td colSpan="10"><div><b>{g.nome}</b><span>{g.itens.length} equipes</span><strong>{g.itens.reduce((s,x)=>s+Number(x.hps||0),0)} HPs</strong></div></td></tr>{g.itens.map(x=><tr key={x.id} className="sheet-data-row"><td className="fusion-cell"><input type="checkbox" disabled={!editavel} checked={!!x.fusion_machine} onChange={e=>alterarRota(x.id,'fusion_machine',e.target.checked)}/></td><td><CelulaEditavel valor={x.technician} editavel={editavel} onSalvar={v=>alterarRota(x.id,'technician',v)} classe="tech-input"/></td><td><CelulaEditavel valor={x.assistant} editavel={editavel} onSalvar={v=>alterarRota(x.id,'assistant',v)} classe="assistant-input"/></td><td><CelulaEditavel valor={x.address} editavel={editavel} onSalvar={v=>alterarRota(x.id,'address',v)} classe="address-input"/></td><td><CelulaEditavel valor={x.hps||0} tipo="number" editavel={editavel} onSalvar={v=>alterarRota(x.id,'hps',v)} classe="number-input"/></td><td><CelulaEditavel valor={x.blocks||0} tipo="number" editavel={editavel} onSalvar={v=>alterarRota(x.id,'blocks',v)} classe="number-input"/></td><td><select disabled={!editavel} className="sheet-select status" value={STATUS.includes(x.status)?x.status:''} onChange={e=>alterarRota(x.id,'status',e.target.value)}><option value="" disabled>{x.status||'Status'}</option>{STATUS.map(s=><option key={s}>{s}</option>)}</select></td><td><input className="sheet-input date-input" disabled={!editavel} type="date" value={x.start_date||''} onChange={e=>alterarRota(x.id,'start_date',e.target.value||null)}/></td><td><select disabled={!editavel} className="sheet-select synergy-select" value={x.synergy||''} onChange={e=>alterarRota(x.id,'synergy',e.target.value)}><option value="">—</option><option>COM SINERGIA</option><option>SEM SINERGIA</option></select></td><td><select disabled={!editavel} className="sheet-select project-select" value={x.project_type||''} onChange={e=>alterarRota(x.id,'project_type',e.target.value)}><option value="">—</option><option>PROJETO F</option><option>ONGOING</option><option>HFC</option></select></td></tr>)}</React.Fragment>)}</tbody></table></div></div>;
}

function RotaQuadro({lista,alterarRota,editavel}){
  const cols=[['EM CONSTRUÇÃO','Em construção'],['TENTANDO ACESSO','Tentando acesso'],['CONSTRUÍDO','Concluídos'],['ACESSO NEGADO','Acesso negado'],['OBSTRUÇÃO','Obstrução']];
  const grupo=(status)=>lista.filter(x=>status==='CONSTRUÍDO'?construida(x.status):n(x.status)===status);
  const ids=new Set(cols.flatMap(([s])=>grupo(s).map(x=>x.id))); const outros=lista.filter(x=>!ids.has(x.id));
  return <div className="board-wrap"><div className="board">{[...cols,...(outros.length?[['OUTROS','Outros']]:[])].map(([status,titulo])=>{const cards=status==='OUTROS'?outros:grupo(status);return <section className="board-column" key={status} onDragOver={e=>editavel&&e.preventDefault()} onDrop={e=>{if(!editavel||status==='OUTROS')return;const id=e.dataTransfer.getData('text/plain');if(id)alterarRota(id,'status',status)}}><header><div><i className={`status-dot s-${status.replaceAll(' ','-')}`}/><b>{titulo}</b><span>{cards.length}</span></div><button>＋</button></header><div className="board-cards">{cards.map(x=><article className="task-card" key={x.id} draggable={editavel} onDragStart={e=>e.dataTransfer.setData('text/plain',x.id)}><div className="task-card-top"><span className="city-chip">{nomeCidade(x.city_id).split(' - ')[0]}</span><button>•••</button></div><h3>{x.technician||'Sem técnico'}</h3><p>{x.address||'Endereço não informado'}</p><div className="task-meta"><span>{x.hps||0} HPs</span><span>{x.blocks||0} blocos</span></div><div className="task-footer"><div className="mini-avatar">{(x.technician||'--').slice(0,2).toUpperCase()}</div><small>{fmt(x.start_date)}</small><span className="project-chip">{x.project_type||'—'}</span></div></article>)}</div><button className="column-add">＋ Adicionar tarefa</button></section>})}</div></div>;
}

function NovaRota({onClose,carregar,auditar}){const [f,setF]=useState({city_id:'NATAL',technician:'',assistant:'',address:'',hps:0,blocks:0,status:'EM CONSTRUÇÃO',start_date:hoje(),synergy:'SEM SINERGIA',project_type:'PROJETO F',fusion_machine:false});async function salvar(e){e.preventDefault();const row={...f,hps:Number(f.hps),blocks:Number(f.blocks),property_code:codigoEndereco(f.address),route_date:hoje()};const {data,error}=await supabase.from('route_daily').insert(row).select('id').single();if(!error){await auditar('ADICIONAR_ROTA','route_daily',data.id,{technician:f.technician,address:f.address});await carregar();onClose()}}return <form className="quick-form" onSubmit={salvar}><Campo label="Cidade"><select value={f.city_id} onChange={e=>setF({...f,city_id:e.target.value})}>{CIDADES.map(([id,nome])=><option value={id} key={id}>{nome}</option>)}</select></Campo><Campo label="Técnico"><input required value={f.technician} onChange={e=>setF({...f,technician:e.target.value})}/></Campo><Campo label="Auxiliar"><input value={f.assistant} onChange={e=>setF({...f,assistant:e.target.value})}/></Campo><div className="wide"><Campo label="Endereço / código"><input required value={f.address} onChange={e=>setF({...f,address:e.target.value})}/></Campo></div><Campo label="HPs"><input type="number" value={f.hps} onChange={e=>setF({...f,hps:e.target.value})}/></Campo><Campo label="Blocos"><input type="number" value={f.blocks} onChange={e=>setF({...f,blocks:e.target.value})}/></Campo><Campo label="Sinergia"><select value={f.synergy} onChange={e=>setF({...f,synergy:e.target.value})}><option>COM SINERGIA</option><option>SEM SINERGIA</option></select></Campo><Campo label="Projeto"><select value={f.project_type} onChange={e=>setF({...f,project_type:e.target.value})}><option>PROJETO F</option><option>ONGOING</option><option>HFC</option></select></Campo><div className="form-actions"><button type="button" className="ghost" onClick={onClose}>Cancelar</button><button className="primary">Salvar</button></div></form>}

function Base({base}){const [busca,setBusca]=useState(''),[cidade,setCidade]=useState('TODAS');const lista=useMemo(()=>base.filter(x=>{const t=[x.property_code,x.address,x.name,x.team,x.status].join(' ').toLowerCase();return(!busca||t.includes(busca.toLowerCase()))&&(cidade==='TODAS'||x.city_id===cidade)}),[base,busca,cidade]);function exportar(){const c=['city_id','team','project_type','synergy','property_code','address','name','hps','construction_date','month_label','status','inspection','measured','notes'],esc=v=>`"${String(v??'').replaceAll('"','""')}"`,csv=[c.join(';'),...lista.map(x=>c.map(k=>esc(x[k])).join(';'))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`base-geral-${hoje()}.csv`;a.click()}return <><div className="toolbar"><div className="filters"><input className="search" placeholder="Buscar código, endereço, equipe..." value={busca} onChange={e=>setBusca(e.target.value)}/><select value={cidade} onChange={e=>setCidade(e.target.value)}><option value="TODAS">Todas as cidades</option>{CIDADES.map(([id,nome])=><option value={id} key={id}>{nome}</option>)}</select></div><button className="ghost" onClick={exportar}>Exportar CSV</button></div><div className="panel table-panel"><div className="table-meta"><b>{lista.length.toLocaleString('pt-BR')} registros</b><small>Exibindo até 500 por vez</small></div><div className="table-wrap"><table><thead><tr><th>Cidade</th><th>Código</th><th>Endereço / Nome</th><th>Equipe</th><th>HPs</th><th>Construção</th><th>Status</th><th>Projeto</th></tr></thead><tbody>{lista.slice(0,500).map(x=><tr key={x.id}><td>{nomeCidade(x.city_id)}</td><td><b>{x.property_code||'—'}</b></td><td className="address">{x.address}<small>{x.name||''}</small></td><td>{x.team||'—'}</td><td>{x.hps}</td><td>{fmt(x.construction_date)}</td><td><span className="badge">{x.status||'—'}</span></td><td>{x.project_type||'—'}</td></tr>)}</tbody></table></div></div></>}

function Historico({historico}){const [busca,setBusca]=useState('');const lista=historico.filter(x=>[x.team,x.address,x.status,x.city_id].join(' ').toLowerCase().includes(busca.toLowerCase()));return <><div className="toolbar"><input className="search" placeholder="Filtrar histórico..." value={busca} onChange={e=>setBusca(e.target.value)}/></div><div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Data</th><th>Cidade</th><th>Equipe</th><th>Endereço</th><th>HPs</th><th>Blocos</th><th>Status</th><th>Início</th><th>Observação</th></tr></thead><tbody>{lista.slice(0,500).map(x=><tr key={x.id}><td>{fmt(x.occurred_at)}</td><td>{nomeCidade(x.city_id)}</td><td><b>{x.team||'—'}</b></td><td className="address">{x.address||'—'}</td><td>{x.hps}</td><td>{x.blocks}</td><td><span className="badge warning">{x.status}</span></td><td>{fmt(x.start_date)}</td><td>{x.notes||'—'}</td></tr>)}</tbody></table></div></div></>}

function Fila({proximas,carregar,editavel,auditar}){const [f,setF]=useState({city_id:'NATAL',address:'',status:'PENDENTE',priority:2,notes:'',assigned_to:'',active:true});async function adicionar(e){e.preventDefault();const {data}=await supabase.from('route_queue').insert({...f,priority:Number(f.priority)}).select('id').single();if(data)await auditar('ADICIONAR_FILA','route_queue',data.id,{address:f.address});setF({...f,address:'',notes:'',assigned_to:''});carregar()}async function enviar(x){await supabase.from('route_daily').insert({city_id:x.city_id,technician:x.assigned_to||'',assistant:'',address:x.address,hps:0,blocks:0,status:'TENTANDO ACESSO',start_date:hoje(),route_date:hoje(),synergy:'SEM SINERGIA',project_type:'PROJETO F'});await supabase.from('route_queue').update({active:false,status:'ENVIADO PARA ROTA'}).eq('id',x.id);carregar()}return <>{editavel&&<form className="quick-form" onSubmit={adicionar}><Campo label="Cidade"><select value={f.city_id} onChange={e=>setF({...f,city_id:e.target.value})}>{CIDADES.map(([id,nome])=><option key={id} value={id}>{nome}</option>)}</select></Campo><div className="wide"><Campo label="Endereço"><input required value={f.address} onChange={e=>setF({...f,address:e.target.value})}/></Campo></div><Campo label="Prioridade"><select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option value="1">Alta</option><option value="2">Média</option><option value="3">Baixa</option></select></Campo><Campo label="Atribuído"><input value={f.assigned_to} onChange={e=>setF({...f,assigned_to:e.target.value})}/></Campo><div className="wide"><Campo label="Observação"><input value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Campo></div><div className="form-actions"><button className="primary">Adicionar à fila</button></div></form>}<div className="cards-list">{proximas.filter(x=>x.active).map(x=><article className="route-card" key={x.id}><div className={`priority p${x.priority}`}>{x.priority===1?'ALTA':x.priority===3?'BAIXA':'MÉDIA'}</div><div><small>{nomeCidade(x.city_id)}</small><h3>{x.address}</h3><p>{x.notes||'Sem observação'} · {x.assigned_to||'Não atribuído'}</p></div>{editavel&&<div className="card-actions"><button className="primary" onClick={()=>enviar(x)}>Enviar para rota</button><button className="icon-btn" onClick={async()=>{await supabase.from('route_queue').delete().eq('id',x.id);carregar()}}>×</button></div>}</article>)}</div>{!proximas.filter(x=>x.active).length&&<Empty texto="Nenhuma próxima rota cadastrada."/>}</>}

function Metas({rota,base}){const ranking=useMemo(()=>{const m={};for(const x of base){if(!x.team)continue;const k=n(x.team);m[k]||={equipe:x.team,hps:0,q:0};m[k].hps+=Number(x.hps||0);if(construida(x.status))m[k].q++}return Object.values(m).sort((a,b)=>b.hps-a.hps).slice(0,30)},[base]);return <div className="grid-2"><Panel titulo="Ranking histórico por HPs" subtitulo="Base Geral"><div className="ranking">{ranking.map((x,i)=><div key={x.equipe}><span>{i+1}</span><div><b>{x.equipe}</b><small>{x.q} construídos</small></div><strong>{x.hps.toLocaleString('pt-BR')} HPs</strong></div>)}</div></Panel><Panel titulo="Produção da rota atual" subtitulo="Equipes em campo"><div className="ranking">{rota.filter(x=>x.technician).sort((a,b)=>b.hps-a.hps).map((x,i)=><div key={x.id}><span>{i+1}</span><div><b>{x.technician}{x.assistant?` / ${x.assistant}`:''}</b><small>{x.status} · {nomeCidade(x.city_id)}</small></div><strong>{x.hps} HPs</strong></div>)}</div></Panel></div>}

function Configuracoes({perfil}){return <div className="settings-grid"><Panel titulo="Infraestrutura" subtitulo="Ambiente atual"><Setting t="Firebase Hosting" d="Publicação web responsiva"/><Setting t="Supabase PostgreSQL + Realtime" d="Banco seguro com RLS por usuário e cidade"/><Setting t="Planilha legada" d="Fonte da migração inicial" status="MIGRADA"/></Panel><Panel titulo="Permissões" subtitulo="Aplicadas pelo banco"><ul className="rules"><li>Perfil atual: <b>{perfil?.role||'—'}</b>.</li><li>Cidade vinculada: <b>{perfil?.city_id||'Acesso geral'}</b>.</li><li>ADMIN/GERENTE gerenciam todas as cidades; CONTROLADOR gerencia a própria cidade.</li><li>Técnicos e auxiliares possuem visualização da própria cidade.</li></ul></Panel></div>}

function Panel({titulo,subtitulo,children}){return <div className="panel"><div className="panel-title"><div><h2>{titulo}</h2><p>{subtitulo}</p></div></div>{children}</div>}
function K({t,v}){return <div><small>{t}</small><b>{v}</b></div>}
function Campo({label,children}){return <div><label>{label}</label>{children}</div>}
function Setting({t,d,status='ATIVO'}){return <div className="setting"><div><b>{t}</b><small>{d}</small></div><span className={status==='ATIVO'?'ok':'muted-badge'}>{status}</span></div>}
function Empty({texto}){return <div className="empty"><span>✓</span><p>{texto}</p></div>}
